/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpertIndexRouteImport } from './routes/expert.index'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ExpertPreviewRouteImport } from './routes/expert.preview'
import { Route as ExpertCoursesIndexRouteImport } from './routes/expert.courses.index'
import { Route as AdminExpertsIndexRouteImport } from './routes/admin.experts.index'
import { Route as ExpertCoursesNewRouteImport } from './routes/expert.courses.new'
import { Route as ExpertCoursesIdRouteImport } from './routes/expert.courses.$id'
import { Route as AlunoCSlugRouteImport } from './routes/aluno.c.$slug'
import { Route as AdminExpertsNewRouteImport } from './routes/admin.experts.new'
import { Route as ExpertCoursesIdStudentsRouteImport } from './routes/expert.courses.$id.students'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertIndexRoute = ExpertIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpertRoute,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/aluno/',
  path: '/aluno/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ExpertPreviewRoute = ExpertPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ExpertRoute,
} as any)
const ExpertCoursesIndexRoute = ExpertCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => ExpertRoute,
} as any)
const AdminExpertsIndexRoute = AdminExpertsIndexRouteImport.update({
  id: '/experts/',
  path: '/experts/',
  getParentRoute: () => AdminRoute,
} as any)
const ExpertCoursesNewRoute = ExpertCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => ExpertRoute,
} as any)
const ExpertCoursesIdRoute = ExpertCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => ExpertRoute,
} as any)
const AlunoCSlugRoute = AlunoCSlugRouteImport.update({
  id: '/aluno/c/$slug',
  path: '/aluno/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExpertsNewRoute = AdminExpertsNewRouteImport.update({
  id: '/experts/new',
  path: '/experts/new',
  getParentRoute: () => AdminRoute,
} as any)
const ExpertCoursesIdStudentsRoute = ExpertCoursesIdStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => ExpertCoursesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/expert': typeof ExpertRouteWithChildren
  '/login': typeof LoginRoute
  '/expert/preview': typeof ExpertPreviewRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/admin/experts/new': typeof AdminExpertsNewRoute
  '/aluno/c/$slug': typeof AlunoCSlugRoute
  '/expert/courses/$id': typeof ExpertCoursesIdRouteWithChildren
  '/expert/courses/new': typeof ExpertCoursesNewRoute
  '/admin/experts/': typeof AdminExpertsIndexRoute
  '/expert/courses/': typeof ExpertCoursesIndexRoute
  '/expert/courses/$id/students': typeof ExpertCoursesIdStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/expert/preview': typeof ExpertPreviewRoute
  '/admin': typeof AdminIndexRoute
  '/aluno': typeof AlunoIndexRoute
  '/expert': typeof ExpertIndexRoute
  '/admin/experts/new': typeof AdminExpertsNewRoute
  '/aluno/c/$slug': typeof AlunoCSlugRoute
  '/expert/courses/$id': typeof ExpertCoursesIdRouteWithChildren
  '/expert/courses/new': typeof ExpertCoursesNewRoute
  '/admin/experts': typeof AdminExpertsIndexRoute
  '/expert/courses': typeof ExpertCoursesIndexRoute
  '/expert/courses/$id/students': typeof ExpertCoursesIdStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/expert': typeof ExpertRouteWithChildren
  '/login': typeof LoginRoute
  '/expert/preview': typeof ExpertPreviewRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/admin/experts/new': typeof AdminExpertsNewRoute
  '/aluno/c/$slug': typeof AlunoCSlugRoute
  '/expert/courses/$id': typeof ExpertCoursesIdRouteWithChildren
  '/expert/courses/new': typeof ExpertCoursesNewRoute
  '/admin/experts/': typeof AdminExpertsIndexRoute
  '/expert/courses/': typeof ExpertCoursesIndexRoute
  '/expert/courses/$id/students': typeof ExpertCoursesIdStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/expert'
    | '/login'
    | '/expert/preview'
    | '/admin/'
    | '/aluno/'
    | '/expert/'
    | '/admin/experts/new'
    | '/aluno/c/$slug'
    | '/expert/courses/$id'
    | '/expert/courses/new'
    | '/admin/experts/'
    | '/expert/courses/'
    | '/expert/courses/$id/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/expert/preview'
    | '/admin'
    | '/aluno'
    | '/expert'
    | '/admin/experts/new'
    | '/aluno/c/$slug'
    | '/expert/courses/$id'
    | '/expert/courses/new'
    | '/admin/experts'
    | '/expert/courses'
    | '/expert/courses/$id/students'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/expert'
    | '/login'
    | '/expert/preview'
    | '/admin/'
    | '/aluno/'
    | '/expert/'
    | '/admin/experts/new'
    | '/aluno/c/$slug'
    | '/expert/courses/$id'
    | '/expert/courses/new'
    | '/admin/experts/'
    | '/expert/courses/'
    | '/expert/courses/$id/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ExpertRoute: typeof ExpertRouteWithChildren
  LoginRoute: typeof LoginRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
  AlunoCSlugRoute: typeof AlunoCSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert/': {
      id: '/expert/'
      path: '/'
      fullPath: '/expert/'
      preLoaderRoute: typeof ExpertIndexRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/aluno'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/expert/preview': {
      id: '/expert/preview'
      path: '/preview'
      fullPath: '/expert/preview'
      preLoaderRoute: typeof ExpertPreviewRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/expert/courses/': {
      id: '/expert/courses/'
      path: '/courses'
      fullPath: '/expert/courses/'
      preLoaderRoute: typeof ExpertCoursesIndexRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/admin/experts/': {
      id: '/admin/experts/'
      path: '/experts'
      fullPath: '/admin/experts/'
      preLoaderRoute: typeof AdminExpertsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/expert/courses/new': {
      id: '/expert/courses/new'
      path: '/courses/new'
      fullPath: '/expert/courses/new'
      preLoaderRoute: typeof ExpertCoursesNewRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/expert/courses/$id': {
      id: '/expert/courses/$id'
      path: '/courses/$id'
      fullPath: '/expert/courses/$id'
      preLoaderRoute: typeof ExpertCoursesIdRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/aluno/c/$slug': {
      id: '/aluno/c/$slug'
      path: '/aluno/c/$slug'
      fullPath: '/aluno/c/$slug'
      preLoaderRoute: typeof AlunoCSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/experts/new': {
      id: '/admin/experts/new'
      path: '/experts/new'
      fullPath: '/admin/experts/new'
      preLoaderRoute: typeof AdminExpertsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/expert/courses/$id/students': {
      id: '/expert/courses/$id/students'
      path: '/students'
      fullPath: '/expert/courses/$id/students'
      preLoaderRoute: typeof ExpertCoursesIdStudentsRouteImport
      parentRoute: typeof ExpertCoursesIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminExpertsNewRoute: typeof AdminExpertsNewRoute
  AdminExpertsIndexRoute: typeof AdminExpertsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminExpertsNewRoute: AdminExpertsNewRoute,
  AdminExpertsIndexRoute: AdminExpertsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ExpertCoursesIdRouteChildren {
  ExpertCoursesIdStudentsRoute: typeof ExpertCoursesIdStudentsRoute
}

const ExpertCoursesIdRouteChildren: ExpertCoursesIdRouteChildren = {
  ExpertCoursesIdStudentsRoute: ExpertCoursesIdStudentsRoute,
}

const ExpertCoursesIdRouteWithChildren = ExpertCoursesIdRoute._addFileChildren(
  ExpertCoursesIdRouteChildren,
)

interface ExpertRouteChildren {
  ExpertPreviewRoute: typeof ExpertPreviewRoute
  ExpertIndexRoute: typeof ExpertIndexRoute
  ExpertCoursesIdRoute: typeof ExpertCoursesIdRouteWithChildren
  ExpertCoursesNewRoute: typeof ExpertCoursesNewRoute
  ExpertCoursesIndexRoute: typeof ExpertCoursesIndexRoute
}

const ExpertRouteChildren: ExpertRouteChildren = {
  ExpertPreviewRoute: ExpertPreviewRoute,
  ExpertIndexRoute: ExpertIndexRoute,
  ExpertCoursesIdRoute: ExpertCoursesIdRouteWithChildren,
  ExpertCoursesNewRoute: ExpertCoursesNewRoute,
  ExpertCoursesIndexRoute: ExpertCoursesIndexRoute,
}

const ExpertRouteWithChildren =
  ExpertRoute._addFileChildren(ExpertRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ExpertRoute: ExpertRouteWithChildren,
  LoginRoute: LoginRoute,
  AlunoIndexRoute: AlunoIndexRoute,
  AlunoCSlugRoute: AlunoCSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
