/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as ExpertIndexRouteImport } from './routes/expert.index'
import { Route as AlunoIndexRouteImport } from './routes/aluno.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutosComunicaPascomRouteImport } from './routes/produtos.comunica-pascom'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'
import { Route as ExpertProfileRouteImport } from './routes/expert.profile'
import { Route as ExpertPreviewRouteImport } from './routes/expert.preview'
import { Route as CheckoutSucessoRouteImport } from './routes/checkout.sucesso'
import { Route as CheckoutPendenteRouteImport } from './routes/checkout.pendente'
import { Route as CheckoutFalhouRouteImport } from './routes/checkout.falhou'
import { Route as AlunoPerfilRouteImport } from './routes/aluno.perfil'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminMaintenanceRouteImport } from './routes/admin.maintenance'
import { Route as AdminInvitationsRouteImport } from './routes/admin.invitations'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCommunitiesRouteImport } from './routes/admin.communities'
import { Route as AdminAccessRouteImport } from './routes/admin.access'
import { Route as ExpertCoursesIndexRouteImport } from './routes/expert.courses.index'
import { Route as AdminExpertsIndexRouteImport } from './routes/admin.experts.index'
import { Route as ExpertCoursesNewRouteImport } from './routes/expert.courses.new'
import { Route as ExpertCoursesIdRouteImport } from './routes/expert.courses.$id'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AlunoCSlugRouteImport } from './routes/aluno.c.$slug'
import { Route as AdminExpertsNewRouteImport } from './routes/admin.experts.new'
import { Route as AdminExpertsIdRouteImport } from './routes/admin.experts.$id'
import { Route as ExpertCoursesIdStudentsRouteImport } from './routes/expert.courses.$id.students'
import { Route as ExpertCoursesIdLivePostIdRouteImport } from './routes/expert.courses.$id.live.$postId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertIndexRoute = ExpertIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpertRoute,
} as any)
const AlunoIndexRoute = AlunoIndexRouteImport.update({
  id: '/aluno/',
  path: '/aluno/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutosComunicaPascomRoute = ProdutosComunicaPascomRouteImport.update({
  id: '/produtos/comunica-pascom',
  path: '/produtos/comunica-pascom',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/produtos/$slug',
  path: '/produtos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertProfileRoute = ExpertProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ExpertRoute,
} as any)
const ExpertPreviewRoute = ExpertPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ExpertRoute,
} as any)
const CheckoutSucessoRoute = CheckoutSucessoRouteImport.update({
  id: '/checkout/sucesso',
  path: '/checkout/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPendenteRoute = CheckoutPendenteRouteImport.update({
  id: '/checkout/pendente',
  path: '/checkout/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutFalhouRoute = CheckoutFalhouRouteImport.update({
  id: '/checkout/falhou',
  path: '/checkout/falhou',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoPerfilRoute = AlunoPerfilRouteImport.update({
  id: '/aluno/perfil',
  path: '/aluno/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitationsRoute = AdminInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunitiesRoute = AdminCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const ExpertCoursesIndexRoute = ExpertCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => ExpertRoute,
} as any)
const AdminExpertsIndexRoute = AdminExpertsIndexRouteImport.update({
  id: '/experts/',
  path: '/experts/',
  getParentRoute: () => AdminRoute,
} as any)
const ExpertCoursesNewRoute = ExpertCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => ExpertRoute,
} as any)
const ExpertCoursesIdRoute = ExpertCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => ExpertRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoCSlugRoute = AlunoCSlugRouteImport.update({
  id: '/aluno/c/$slug',
  path: '/aluno/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExpertsNewRoute = AdminExpertsNewRouteImport.update({
  id: '/experts/new',
  path: '/experts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExpertsIdRoute = AdminExpertsIdRouteImport.update({
  id: '/experts/$id',
  path: '/experts/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ExpertCoursesIdStudentsRoute = ExpertCoursesIdStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => ExpertCoursesIdRoute,
} as any)
const ExpertCoursesIdLivePostIdRoute =
  ExpertCoursesIdLivePostIdRouteImport.update({
    id: '/live/$postId',
    path: '/live/$postId',
    getParentRoute: () => ExpertCoursesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/expert': typeof ExpertRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/support': typeof AdminSupportRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/checkout/falhou': typeof CheckoutFalhouRoute
  '/checkout/pendente': typeof CheckoutPendenteRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/expert/preview': typeof ExpertPreviewRoute
  '/expert/profile': typeof ExpertProfileRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/comunica-pascom': typeof ProdutosComunicaPascomRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/admin/experts/$id': typeof AdminExpertsIdRoute
  '/admin/experts/new': typeof AdminExpertsNewRoute
  '/aluno/c/$slug': typeof AlunoCSlugRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/expert/courses/$id': typeof ExpertCoursesIdRouteWithChildren
  '/expert/courses/new': typeof ExpertCoursesNewRoute
  '/admin/experts/': typeof AdminExpertsIndexRoute
  '/expert/courses/': typeof ExpertCoursesIndexRoute
  '/expert/courses/$id/students': typeof ExpertCoursesIdStudentsRoute
  '/expert/courses/$id/live/$postId': typeof ExpertCoursesIdLivePostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/support': typeof AdminSupportRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/checkout/falhou': typeof CheckoutFalhouRoute
  '/checkout/pendente': typeof CheckoutPendenteRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/expert/preview': typeof ExpertPreviewRoute
  '/expert/profile': typeof ExpertProfileRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/comunica-pascom': typeof ProdutosComunicaPascomRoute
  '/admin': typeof AdminIndexRoute
  '/aluno': typeof AlunoIndexRoute
  '/expert': typeof ExpertIndexRoute
  '/produtos': typeof ProdutosIndexRoute
  '/admin/experts/$id': typeof AdminExpertsIdRoute
  '/admin/experts/new': typeof AdminExpertsNewRoute
  '/aluno/c/$slug': typeof AlunoCSlugRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/expert/courses/$id': typeof ExpertCoursesIdRouteWithChildren
  '/expert/courses/new': typeof ExpertCoursesNewRoute
  '/admin/experts': typeof AdminExpertsIndexRoute
  '/expert/courses': typeof ExpertCoursesIndexRoute
  '/expert/courses/$id/students': typeof ExpertCoursesIdStudentsRoute
  '/expert/courses/$id/live/$postId': typeof ExpertCoursesIdLivePostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/expert': typeof ExpertRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/support': typeof AdminSupportRoute
  '/aluno/perfil': typeof AlunoPerfilRoute
  '/checkout/falhou': typeof CheckoutFalhouRoute
  '/checkout/pendente': typeof CheckoutPendenteRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/expert/preview': typeof ExpertPreviewRoute
  '/expert/profile': typeof ExpertProfileRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/comunica-pascom': typeof ProdutosComunicaPascomRoute
  '/admin/': typeof AdminIndexRoute
  '/aluno/': typeof AlunoIndexRoute
  '/expert/': typeof ExpertIndexRoute
  '/produtos/': typeof ProdutosIndexRoute
  '/admin/experts/$id': typeof AdminExpertsIdRoute
  '/admin/experts/new': typeof AdminExpertsNewRoute
  '/aluno/c/$slug': typeof AlunoCSlugRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/expert/courses/$id': typeof ExpertCoursesIdRouteWithChildren
  '/expert/courses/new': typeof ExpertCoursesNewRoute
  '/admin/experts/': typeof AdminExpertsIndexRoute
  '/expert/courses/': typeof ExpertCoursesIndexRoute
  '/expert/courses/$id/students': typeof ExpertCoursesIdStudentsRoute
  '/expert/courses/$id/live/$postId': typeof ExpertCoursesIdLivePostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/expert'
    | '/login'
    | '/reset-password'
    | '/admin/access'
    | '/admin/communities'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/invitations'
    | '/admin/maintenance'
    | '/admin/produtos'
    | '/admin/students'
    | '/admin/support'
    | '/aluno/perfil'
    | '/checkout/falhou'
    | '/checkout/pendente'
    | '/checkout/sucesso'
    | '/expert/preview'
    | '/expert/profile'
    | '/produtos/$slug'
    | '/produtos/comunica-pascom'
    | '/admin/'
    | '/aluno/'
    | '/expert/'
    | '/produtos/'
    | '/admin/experts/$id'
    | '/admin/experts/new'
    | '/aluno/c/$slug'
    | '/api/public/stripe-webhook'
    | '/expert/courses/$id'
    | '/expert/courses/new'
    | '/admin/experts/'
    | '/expert/courses/'
    | '/expert/courses/$id/students'
    | '/expert/courses/$id/live/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/admin/access'
    | '/admin/communities'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/invitations'
    | '/admin/maintenance'
    | '/admin/produtos'
    | '/admin/students'
    | '/admin/support'
    | '/aluno/perfil'
    | '/checkout/falhou'
    | '/checkout/pendente'
    | '/checkout/sucesso'
    | '/expert/preview'
    | '/expert/profile'
    | '/produtos/$slug'
    | '/produtos/comunica-pascom'
    | '/admin'
    | '/aluno'
    | '/expert'
    | '/produtos'
    | '/admin/experts/$id'
    | '/admin/experts/new'
    | '/aluno/c/$slug'
    | '/api/public/stripe-webhook'
    | '/expert/courses/$id'
    | '/expert/courses/new'
    | '/admin/experts'
    | '/expert/courses'
    | '/expert/courses/$id/students'
    | '/expert/courses/$id/live/$postId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/expert'
    | '/login'
    | '/reset-password'
    | '/admin/access'
    | '/admin/communities'
    | '/admin/content'
    | '/admin/courses'
    | '/admin/invitations'
    | '/admin/maintenance'
    | '/admin/produtos'
    | '/admin/students'
    | '/admin/support'
    | '/aluno/perfil'
    | '/checkout/falhou'
    | '/checkout/pendente'
    | '/checkout/sucesso'
    | '/expert/preview'
    | '/expert/profile'
    | '/produtos/$slug'
    | '/produtos/comunica-pascom'
    | '/admin/'
    | '/aluno/'
    | '/expert/'
    | '/produtos/'
    | '/admin/experts/$id'
    | '/admin/experts/new'
    | '/aluno/c/$slug'
    | '/api/public/stripe-webhook'
    | '/expert/courses/$id'
    | '/expert/courses/new'
    | '/admin/experts/'
    | '/expert/courses/'
    | '/expert/courses/$id/students'
    | '/expert/courses/$id/live/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ExpertRoute: typeof ExpertRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AlunoPerfilRoute: typeof AlunoPerfilRoute
  CheckoutFalhouRoute: typeof CheckoutFalhouRoute
  CheckoutPendenteRoute: typeof CheckoutPendenteRoute
  CheckoutSucessoRoute: typeof CheckoutSucessoRoute
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  ProdutosComunicaPascomRoute: typeof ProdutosComunicaPascomRoute
  AlunoIndexRoute: typeof AlunoIndexRoute
  ProdutosIndexRoute: typeof ProdutosIndexRoute
  AlunoCSlugRoute: typeof AlunoCSlugRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/produtos'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert/': {
      id: '/expert/'
      path: '/'
      fullPath: '/expert/'
      preLoaderRoute: typeof ExpertIndexRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/aluno/': {
      id: '/aluno/'
      path: '/aluno'
      fullPath: '/aluno/'
      preLoaderRoute: typeof AlunoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produtos/comunica-pascom': {
      id: '/produtos/comunica-pascom'
      path: '/produtos/comunica-pascom'
      fullPath: '/produtos/comunica-pascom'
      preLoaderRoute: typeof ProdutosComunicaPascomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/produtos/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert/profile': {
      id: '/expert/profile'
      path: '/profile'
      fullPath: '/expert/profile'
      preLoaderRoute: typeof ExpertProfileRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/expert/preview': {
      id: '/expert/preview'
      path: '/preview'
      fullPath: '/expert/preview'
      preLoaderRoute: typeof ExpertPreviewRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/checkout/sucesso': {
      id: '/checkout/sucesso'
      path: '/checkout/sucesso'
      fullPath: '/checkout/sucesso'
      preLoaderRoute: typeof CheckoutSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/pendente': {
      id: '/checkout/pendente'
      path: '/checkout/pendente'
      fullPath: '/checkout/pendente'
      preLoaderRoute: typeof CheckoutPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/falhou': {
      id: '/checkout/falhou'
      path: '/checkout/falhou'
      fullPath: '/checkout/falhou'
      preLoaderRoute: typeof CheckoutFalhouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/perfil': {
      id: '/aluno/perfil'
      path: '/aluno/perfil'
      fullPath: '/aluno/perfil'
      preLoaderRoute: typeof AlunoPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invitations': {
      id: '/admin/invitations'
      path: '/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AdminInvitationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities': {
      id: '/admin/communities'
      path: '/communities'
      fullPath: '/admin/communities'
      preLoaderRoute: typeof AdminCommunitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/expert/courses/': {
      id: '/expert/courses/'
      path: '/courses'
      fullPath: '/expert/courses/'
      preLoaderRoute: typeof ExpertCoursesIndexRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/admin/experts/': {
      id: '/admin/experts/'
      path: '/experts'
      fullPath: '/admin/experts/'
      preLoaderRoute: typeof AdminExpertsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/expert/courses/new': {
      id: '/expert/courses/new'
      path: '/courses/new'
      fullPath: '/expert/courses/new'
      preLoaderRoute: typeof ExpertCoursesNewRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/expert/courses/$id': {
      id: '/expert/courses/$id'
      path: '/courses/$id'
      fullPath: '/expert/courses/$id'
      preLoaderRoute: typeof ExpertCoursesIdRouteImport
      parentRoute: typeof ExpertRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/c/$slug': {
      id: '/aluno/c/$slug'
      path: '/aluno/c/$slug'
      fullPath: '/aluno/c/$slug'
      preLoaderRoute: typeof AlunoCSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/experts/new': {
      id: '/admin/experts/new'
      path: '/experts/new'
      fullPath: '/admin/experts/new'
      preLoaderRoute: typeof AdminExpertsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experts/$id': {
      id: '/admin/experts/$id'
      path: '/experts/$id'
      fullPath: '/admin/experts/$id'
      preLoaderRoute: typeof AdminExpertsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/expert/courses/$id/students': {
      id: '/expert/courses/$id/students'
      path: '/students'
      fullPath: '/expert/courses/$id/students'
      preLoaderRoute: typeof ExpertCoursesIdStudentsRouteImport
      parentRoute: typeof ExpertCoursesIdRoute
    }
    '/expert/courses/$id/live/$postId': {
      id: '/expert/courses/$id/live/$postId'
      path: '/live/$postId'
      fullPath: '/expert/courses/$id/live/$postId'
      preLoaderRoute: typeof ExpertCoursesIdLivePostIdRouteImport
      parentRoute: typeof ExpertCoursesIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminCommunitiesRoute: typeof AdminCommunitiesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminInvitationsRoute: typeof AdminInvitationsRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminExpertsIdRoute: typeof AdminExpertsIdRoute
  AdminExpertsNewRoute: typeof AdminExpertsNewRoute
  AdminExpertsIndexRoute: typeof AdminExpertsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminCommunitiesRoute: AdminCommunitiesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminInvitationsRoute: AdminInvitationsRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminExpertsIdRoute: AdminExpertsIdRoute,
  AdminExpertsNewRoute: AdminExpertsNewRoute,
  AdminExpertsIndexRoute: AdminExpertsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ExpertCoursesIdRouteChildren {
  ExpertCoursesIdStudentsRoute: typeof ExpertCoursesIdStudentsRoute
  ExpertCoursesIdLivePostIdRoute: typeof ExpertCoursesIdLivePostIdRoute
}

const ExpertCoursesIdRouteChildren: ExpertCoursesIdRouteChildren = {
  ExpertCoursesIdStudentsRoute: ExpertCoursesIdStudentsRoute,
  ExpertCoursesIdLivePostIdRoute: ExpertCoursesIdLivePostIdRoute,
}

const ExpertCoursesIdRouteWithChildren = ExpertCoursesIdRoute._addFileChildren(
  ExpertCoursesIdRouteChildren,
)

interface ExpertRouteChildren {
  ExpertPreviewRoute: typeof ExpertPreviewRoute
  ExpertProfileRoute: typeof ExpertProfileRoute
  ExpertIndexRoute: typeof ExpertIndexRoute
  ExpertCoursesIdRoute: typeof ExpertCoursesIdRouteWithChildren
  ExpertCoursesNewRoute: typeof ExpertCoursesNewRoute
  ExpertCoursesIndexRoute: typeof ExpertCoursesIndexRoute
}

const ExpertRouteChildren: ExpertRouteChildren = {
  ExpertPreviewRoute: ExpertPreviewRoute,
  ExpertProfileRoute: ExpertProfileRoute,
  ExpertIndexRoute: ExpertIndexRoute,
  ExpertCoursesIdRoute: ExpertCoursesIdRouteWithChildren,
  ExpertCoursesNewRoute: ExpertCoursesNewRoute,
  ExpertCoursesIndexRoute: ExpertCoursesIndexRoute,
}

const ExpertRouteWithChildren =
  ExpertRoute._addFileChildren(ExpertRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ExpertRoute: ExpertRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AlunoPerfilRoute: AlunoPerfilRoute,
  CheckoutFalhouRoute: CheckoutFalhouRoute,
  CheckoutPendenteRoute: CheckoutPendenteRoute,
  CheckoutSucessoRoute: CheckoutSucessoRoute,
  ProdutosSlugRoute: ProdutosSlugRoute,
  ProdutosComunicaPascomRoute: ProdutosComunicaPascomRoute,
  AlunoIndexRoute: AlunoIndexRoute,
  ProdutosIndexRoute: ProdutosIndexRoute,
  AlunoCSlugRoute: AlunoCSlugRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
